### ISSUE TITLE
Unable to location .toc files

### ISSUE THREAD

**Issue by BillChirico** [p3lim/toc-interface-updater#5]
Hello,

The workflow is unable to locate my .toc files. I even tried working directories as well.

[Repo Link
](https://github.com/BillChirico/BapesAutoMerge)[Workflow Link](https://github.com/BillChirico/BapesAutoMerge/blob/master/.github/workflows/update-metadata.yml)

**Comment by p3lim** [comment]
Don't change the working directory to `src/`, your toc files aren't in there.
